SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[vwCRMLoad_FanProfile_Custom_Update]
AS
SELECT  
	 z.[crm_id] Id
	,b.SSB_CRMSYSTEM_SSID_Winner__c										--,c.SSB_CRMSYSTEM_SSID_Winner__c
	,b.SSB_CRMSYSTEM_DimCustomerID__c									--,c.SSB_CRMSYSTEM_DimCustomerID__c
	,b.SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c						--,c.SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c
	,b.SSB_CRMSYSTEM_SSID_TIX__c										--,c.SSB_CRMSYSTEM_SSID_TIX__c
FROM dbo.[vwCRMLoad_fanprofile_Std_Prep] a
INNER JOIN dbo.[Account_Custom] b ON [a].[SSB_CRMSYSTEM_ACCT_ID__c] = b.[SSB_CRMSYSTEM_ACCT_ID]
INNER JOIN dbo.Account z ON a.[SSB_CRMSYSTEM_ACCT_ID__c] = z.[SSB_CRMSYSTEM_ACCT_ID]
LEFT JOIN  prodcopy.Fan_Profile__c c ON z.[crm_id] = c.ID
WHERE z.[SSB_CRMSYSTEM_ACCT_ID] <> z.[crm_id]
--AND  (1=2
	--OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST(  b.SSB_CRMSYSTEM_SSID_Winner__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_SSID_Winner__c AS VARCHAR(MAX)))),'')) 
--	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_DimCustomerID__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST(  c.SSB_CRMSYSTEM_DimCustomerID__c AS VARCHAR(MAX)))),'')) 
--	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c AS VARCHAR(MAX)))),''))
--	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_SSID_TIX__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_SSID_TIX__c AS VARCHAR(MAX)))),''))
--)
GO
